services:
  currency-exchange:
    image: slux83/currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 1g
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion:
    image: slux83/currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 1g
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: slux83/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 1g
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - zipkin-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

  naming-server:
    image: slux83/naming-server:0.0.1-SNAPSHOT
    mem_limit: 1g
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 1g
    ports:
      - "9411:9411"
    networks:
      - currency-network

networks:
  currency-network: